# Generated by Django 4.1.7 on 2023-03-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fizlitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('oname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exemple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.bolim')),
                ('fiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.fizlitsa')),
            ],
        ),
    ]
