# Generated by Django 4.1.7 on 2023-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_bolim_fizlitsa_exemple'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemple',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
