# Generated by Django 4.1.7 on 2023-04-28 16:29

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firs_name',
            field=models.CharField(blank=True, default='ISM', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='FAMILYA', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default/avatar.png', upload_to=login.models.get_image_path),
        ),
    ]
