# Generated by Django 4.1.7 on 2023-05-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_lavozim_hodim_lavozim'),
        ('login', '0004_alter_profile_firs_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hodim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.hodim'),
        ),
    ]
