# Generated by Django 4.1.7 on 2023-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_narxnoma_remove_exemple_name_exemple_summa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemple',
            name='miqdor',
            field=models.FloatField(null=True),
        ),
    ]
