# Generated by Django 4.1.7 on 2023-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_exemple_miqdor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizlitsa',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fizlitsa',
            name='jins',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fizlitsa',
            name='jshir',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='fizlitsa',
            name='pasport',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
