# Generated by Django 4.1.7 on 2023-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_fizlitsa_birth_fizlitsa_jins_fizlitsa_jshir_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemple',
        ),
    ]
