# Generated by Django 4.1.7 on 2023-03-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_exemple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.bolim')),
                ('fizlitsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.fizlitsa')),
                ('shtat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.shtat')),
            ],
        ),
    ]
