# Generated by Django 4.1.7 on 2023-03-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_oylar_naryad'),
    ]

    operations = [
        migrations.AddField(
            model_name='naryad',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.bolim'),
        ),
        migrations.AlterField(
            model_name='naryad',
            name='summa',
            field=models.FloatField(blank=True),
        ),
    ]
