# Generated by Django 4.1.7 on 2023-03-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_naryad_bolim_alter_naryad_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naryad',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='naryad',
            name='hodim',
        ),
        migrations.RemoveField(
            model_name='naryad',
            name='miqdor',
        ),
        migrations.RemoveField(
            model_name='naryad',
            name='narxnoma',
        ),
        migrations.RemoveField(
            model_name='naryad',
            name='oylar',
        ),
        migrations.RemoveField(
            model_name='naryad',
            name='summa',
        ),
    ]
