# Generated by Django 4.1.7 on 2023-03-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_naryad_bolim_remove_naryad_hodim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naryad',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.bolim'),
        ),
        migrations.AddField(
            model_name='naryad',
            name='hodim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.fizlitsa'),
        ),
        migrations.AddField(
            model_name='naryad',
            name='miqdor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='naryad',
            name='narxnoma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.narxnoma'),
        ),
        migrations.AddField(
            model_name='naryad',
            name='oy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.oylar'),
        ),
        migrations.AddField(
            model_name='naryad',
            name='summa',
            field=models.FloatField(null=True),
        ),
    ]
