# Generated by Django 4.1.7 on 2023-03-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_naryad_bolim_naryad_hodim_naryad_miqdor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizlitsa',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.bolim'),
        ),
    ]
