# Generated by Django 4.2 on 2023-04-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_num', models.IntegerField()),
                ('Agranom_full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Massiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GBrigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_num', models.CharField(max_length=2)),
                ('brigadir', models.CharField(max_length=20)),
                ('gektar', models.FloatField()),
                ('reja', models.FloatField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.hudud')),
                ('massiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.massiv')),
            ],
        ),
    ]
