# Generated by Django 3.2.9 on 2023-04-22 14:31

from django.db import migrations, models
import django.db.models.deletion
import homes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('jshir', models.CharField(max_length=14)),
                ('pasport', models.CharField(blank=True, max_length=9, null=True)),
                ('karta', models.CharField(blank=True, max_length=16, null=True)),
                ('mudati', models.CharField(blank=True, max_length=5, null=True)),
                ('pic', models.ImageField(default='default/avatar.png', upload_to=homes.models.get_image_path)),
                ('bolim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_num', models.CharField(max_length=1)),
                ('Agranom_full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Massiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(max_length=20)),
                ('oy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OmborG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reja', models.FloatField(null=True)),
                ('sentner', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.FloatField(default=0)),
                ('soliq', models.FloatField(default=0)),
                ('inps', models.FloatField(default=0)),
                ('aliment', models.FloatField(default=0)),
                ('boshqa', models.FloatField(default=0)),
                ('qoldiq', models.FloatField(blank=True, null=True)),
                ('oy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.month')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.hodim')),
            ],
        ),
        migrations.AddField(
            model_name='hodim',
            name='lavozim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.lavozim'),
        ),
        migrations.CreateModel(
            name='GBrigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_num', models.CharField(max_length=2)),
                ('brigadir', models.CharField(max_length=30)),
                ('gektar', models.FloatField()),
                ('reja', models.FloatField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.hudud')),
                ('massiv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.massiv')),
            ],
        ),
        migrations.CreateModel(
            name='Galla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('yuk_num', models.CharField(max_length=3)),
                ('tr_marka', models.CharField(choices=[('ЗИЛ', 'ЗИЛ'), ('КАМАЗ', 'КАМАЗ'), ('БОШКА', 'БОШКА')], max_length=20)),
                ('tr_num', models.CharField(max_length=20)),
                ('tr_name', models.CharField(max_length=30)),
                ('imzo', models.BooleanField(default=False)),
                ('brutto', models.FloatField(blank=True, null=True)),
                ('tara', models.FloatField(blank=True, null=True)),
                ('sofVazn', models.IntegerField(blank=True, default=0, null=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.gbrigada')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.omborg')),
            ],
        ),
    ]
