# Generated by Django 4.1.7 on 2023-04-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodim',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='hodim',
            name='lavozim',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='oy',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Bolim',
        ),
        migrations.DeleteModel(
            name='Hodim',
        ),
        migrations.DeleteModel(
            name='Lavozim',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
