# Generated by Django 4.1.7 on 2023-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_omborg_alter_gbrigada_brigadir_alter_hudud_h_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galla',
            name='brutto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galla',
            name='tara',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
