# Generated by Django 4.1.7 on 2023-04-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_bolim_lavozim_omborg_alter_gbrigada_brigadir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(max_length=20)),
                ('oy', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hodim',
            name='karta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hodim',
            name='mudati',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.FloatField(default=0)),
                ('soliq', models.FloatField(default=0)),
                ('inps', models.FloatField(default=0)),
                ('aliment', models.FloatField(default=0)),
                ('boshqa', models.FloatField(default=0)),
                ('oy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.month')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.hodim')),
            ],
        ),
    ]
