# Generated by Django 4.1.7 on 2023-04-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_profile_firs_name_alter_profile_last_name_and_more'),
        ('homes', '0002_remove_hodim_bolim_remove_hodim_lavozim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriya', models.CharField(max_length=2)),
                ('raqami', models.CharField(max_length=9)),
                ('jshir', models.CharField(max_length=14)),
                ('data1', models.DateField()),
                ('data2', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.bolim')),
                ('pasport', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='homes.pasport')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='login.profile')),
            ],
        ),
    ]
