# Generated by Django 4.2 on 2023-04-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_galla_brutto_galla_tara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('jshir', models.CharField(max_length=14)),
                ('Pasport', models.CharField(max_length=9)),
                ('Lavozim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.lavozim')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.bolim')),
            ],
        ),
    ]
