# Generated by Django 4.1.7 on 2023-04-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_month_hodim_karta_hodim_mudati_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='qoldiq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='tegishi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
