# Generated by Django 4.1.7 on 2023-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_bolim_pasport_hodim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqami', models.CharField(max_length=16)),
                ('mudati', models.CharField(max_length=7)),
            ],
        ),
    ]
