# Generated by Django 4.1.7 on 2023-04-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_pay_qoldiq_pay_tegishi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='tegishi',
        ),
    ]
