# Generated by Django 4.2 on 2023-04-10 18:41

from django.db import migrations, models
import homes.models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_bolim_lavozim_hodim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hodim',
            old_name='Lavozim',
            new_name='lavozim',
        ),
        migrations.RenameField(
            model_name='hodim',
            old_name='Pasport',
            new_name='pasport',
        ),
        migrations.AddField(
            model_name='hodim',
            name='pic',
            field=models.ImageField(default='img/default.jpg', upload_to=homes.models.get_image_path),
        ),
    ]
