# Generated by Django 4.1.7 on 2023-04-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.card'),
        ),
    ]
