# Generated by Django 4.2 on 2023-04-10 18:50

from django.db import migrations, models
import homes.models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_rename_lavozim_hodim_lavozim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='pic',
            field=models.ImageField(default='default/avatar.png', upload_to=homes.models.get_image_path),
        ),
    ]
