# Generated by Django 4.1.7 on 2023-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_hodim_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodim',
            name='profile',
        ),
    ]
