# Generated by Django 4.1.7 on 2023-04-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_alter_hodim_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.bolim'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='lavozim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.lavozim'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='pasport',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
