# Generated by Django 4.1.7 on 2023-04-30 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_fizlitsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='fizlitsa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.fizlitsa'),
        ),
    ]
