# Generated by Django 4.1.7 on 2023-04-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_hodim_fizlitsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hodim',
            name='lavozim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.lavozim'),
        ),
    ]
