# Generated by Django 4.1.7 on 2023-05-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_profile_hodim'),
        ('homes', '0009_lavozim_hodim_lavozim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='hodim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.profile'),
        ),
    ]
