# Generated by Django 4.1.7 on 2023-05-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_qoshimcha_ushlanma_alter_hodim_hodim_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='qoshimcha',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='sum1',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='sum2',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='ushlanma',
        ),
    ]
