# Generated by Django 4.1.7 on 2023-05-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0013_ushlanmas_qoshimchas_pay_qoshimcha_pay_ushlanma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='plastik',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='qoshimcha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.qoshimchas'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ushlanma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.ushlanmas'),
        ),
        migrations.AlterField(
            model_name='qoshimchas',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.qoshimcha'),
        ),
        migrations.AlterField(
            model_name='qoshimchas',
            name='sums',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ushlanmas',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.ushlanma'),
        ),
        migrations.AlterField(
            model_name='ushlanmas',
            name='sums',
            field=models.FloatField(default=0),
        ),
    ]
