# Generated by Django 4.1.7 on 2023-05-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_alter_pay_plastik_alter_pay_qoshimcha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshimchas',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.qoshimcha'),
        ),
        migrations.AlterField(
            model_name='qoshimchas',
            name='sums',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ushlanmas',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homes.ushlanma'),
        ),
        migrations.AlterField(
            model_name='ushlanmas',
            name='sums',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
