# Generated by Django 4.1.7 on 2023-05-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0015_alter_qoshimchas_name_alter_qoshimchas_sums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoshimchas',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ushlanmas',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='qoshimcha',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='ushlanma',
        ),
        migrations.DeleteModel(
            name='Qoshimcha',
        ),
        migrations.DeleteModel(
            name='QoshimchaS',
        ),
        migrations.DeleteModel(
            name='Ushlanma',
        ),
        migrations.DeleteModel(
            name='UshlanmaS',
        ),
    ]
