# Generated by Django 4.1.7 on 2023-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0016_remove_qoshimchas_name_remove_ushlanmas_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='qoshimcha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pay',
            name='ushlanma',
            field=models.FloatField(default=0),
        ),
    ]
