# Generated by Django 4.1.7 on 2023-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0018_galla_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='pays',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
